namespace CrmTechTitans.Models.Enumerations
{
    //data according to NIA website
    public enum NaicsIndustryCode
    {
        OilAndGasExtraction = 211,
        MiningAndQuarryingExceptOilAndGas = 212,
        SupportActivitiesForMiningAndOilAndGasExtraction = 213,
        Utilities = 221,
        ConstructionOfBuildings = 236,
        HeavyAndCivilEngineeringConstruction = 237,
        SpecialtyTradeContractors = 238,
        FoodManufacturing = 311,
        BeverageAndTobaccoProductManufacturing = 312,
        ClothingManufacturing = 315,
        WoodProductManufacturing = 321,
        PaperManufacturing = 322,
        PrintingAndRelatedSupportActivities = 323,
        ChemicalManufacturing = 325,
        PlasticsAndRubberProductsManufacturing = 326,
        NonMetallicMineralProductManufacturing = 327,
        PrimaryMetalManufacturing = 331,
        FabricatedMetalProductManufacturing = 332,
        MachineryManufacturing = 333,
        ComputerAndElectronicProductManufacturing = 334,
        ElectricalEquipmentApplianceAndComponentManufacturing = 335,
        TransportationEquipmentManufacturing = 336,
        MiscellaneousManufacturing = 339,
        FarmProductMerchantWholesalers = 411,
        PetroleumAndPetroleumProductsMerchantWholesalers = 412,
        BuildingMaterialAndSuppliesMerchantWholesalers = 416,
        MachineryEquipmentAndSuppliesMerchantWholesalers = 417,
        MiscellaneousMerchantWholesalers = 418,
        BusinessToBusinessElectronicMarketsAndAgentsAndBrokers = 419,
        MotorVehicleAndPartsDealers = 441,
        BuildingMaterialAndGardenEquipmentAndSuppliesDealers = 444,
        GasolineStations = 447,
        AirTransportation = 481,
        RailTransportation = 482,
        WaterTransportation = 483,
        TruckTransportation = 484,
        PipelineTransportation = 486,
        SupportActivitiesForTransportation = 488,
        CouriersAndMessengers = 492,
        WarehousingAndStorage = 493,
        Telecommunications = 517,
        DataProcessingHostingAndRelatedServices = 518,
        OtherInformationServices = 519,
        CreditIntermediationAndRelatedActivities = 522,
        SecuritiesCommodityContractsAndOtherFinancialInvestmentAndRelatedActivities = 523,
        InsuranceCarriersAndRelatedActivities = 524,
        FundsAndOtherFinancialVehicles = 526,
        RealEstate = 531,
        RentalAndLeasingServices = 532,
        ProfessionalScientificAndTechnicalServices = 541,
        ManagementOfCompaniesAndEnterprises = 551,
        AdministrativeAndSupportServices = 561,
        WasteManagementAndRemediationServices = 562,
        EducationalServices = 611,
        RepairAndMaintenance = 811,
        ReligiousGrantMakingCivicAndProfessionalAndSimilarOrganizations = 813,
        FederalGovernmentPublicAdministration = 911,
        ProvincialAndTerritorialPublicAdministration = 912,
        LocalMunicipalAndRegionalPublicAdministration = 913,
        IndustrialConsulting = 1000, // Example for custom value
        Other = 0
    }
}
